---
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:vitest/recommended
  - plugin:prettier/recommended

plugins:
  - vitest
  - prettier

parserOptions:
  project:
    - tsconfig.eslint.json
    - src/tsconfig.json
    - test/tsconfig.json

rules:
  '@typescript-eslint/no-unnecessary-condition':
    - error
    - allowConstantLoopConditions: true
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/naming-convention':
    - error
    - selector:
        - enumMember
        - typeAlias
        - interface
        - enum
        - class
      format:
        - PascalCase
      leadingUnderscore: forbid
      trailingUnderscore: forbid

    - selector:
        - method
        - accessor
        - parameterProperty
      format:
        - strictCamelCase

    - selector:
        - property
      format:
        - strictCamelCase
        - PascalCase
      filter:
        regex: '\d+'
        match: false
      leadingUnderscore: allow
      trailingUnderscore: forbid

    - selector: typeParameter
      format:
        - PascalCase

    - selector: variable
      format:
        - strictCamelCase
        - UPPER_CASE
      leadingUnderscore: allow
      trailingUnderscore: forbid

    - selector: function
      format:
        - strictCamelCase
      leadingUnderscore: forbid
      trailingUnderscore: forbid
  '@typescript-eslint/member-ordering':
    - error
    - default:
        - public-static-field
        - protected-static-field
        - private-static-field
        - static-field
        - public-static-method
        - protected-static-method
        - private-static-method
        - static-method
        - signature
        - public-instance-field
        - protected-instance-field
        - private-instance-field
        - instance-field
        - public-constructor
        - protected-constructor
        - private-constructor
        - constructor
        - public-instance-method
        - protected-instance-method
        - private-instance-method
        - instance-method
  '@typescript-eslint/consistent-type-imports': error
