name: Feature request
description: Suggest an idea for the repository
title: 'request: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Please first [check through existing issues](https://github.com/jo3-l/obscenity/issues) in case your request
        has already been raised.
  - type: textarea
    attributes:
      label: Description
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: Explain the solution you would like to see. Please also provide alternatives to your solution.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
